name: Build and Export Static Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      # 静态导出
      - run: pnpm run export  # 生成静态html文件到 out/

      # 压缩导出目录
      - run: |
          cd out
          zip -r ../site.zip .

      - id: get_version
        run: echo "VERSION=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: "Static Site v${{ env.VERSION }}"
          body: "自动构建静态站点发布 v${{ env.VERSION }}"
          files: site.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
