name: Node.js Build

on:
  push:
    branches: [ main, master ]  # 在推送到主分支时触发
  pull_request:
    branches: [ main, master ]  # 在PR时也触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # 检出代码
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # 指定Node版本，根据你的项目需要调整
        cache: 'npm'       # 缓存npm依赖
        
    - name: Install dependencies
      run: npm ci          # 使用ci比install更严格，适合自动化环境
      
    - name: Build project  # 执行打包命令（根据你的package.json中的build脚本）
      run: npm run build
      
    - name: Archive production artifacts  # 可选：打包生成的文件
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/  # 假设打包输出到dist目录
