name: Static Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate runtime and manifest
        run: pnpm gen:runtime && pnpm gen:manifest

      - name: Build static site (with output: 'export')
        run: pnpm build

      - name: Zip static output
        run: |
          cd .next/export
          zip -r ../../../moontv-static.zip .

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: Static site auto build and release version v${{ env.VERSION }}
          files: moontv-static.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
